### ISSUE TITLE
Integrating a flag for full Takout file processing

### ISSUE THREAD

**Issue by lukehmcc** [garzj/google-photos-migrate#6]
I'm currently maintaining [lukehmcc/exif-wrapper](https://github.com/lukehmcc/exif-wrapper) and think this automatic handling of takeout files would be very useful for this repo. 

Would you be open to a PR to add a new flag like `--takeout` or something that would automatically decompress, organize, and fix the metadata on takeout files? 

Currently this is done via a python script, but I could easily rewrite this in ts.

**Comment by GwynHannay** [comment]
Not to commandeer anyone else's post, but I do want to jump on the contribution bandwagon here. :-)

I found this repo really helpful for processing my mountain of Google Takeout photos and began utilising the additional script under `android-dups` but found my use case quite a bit more extensive. You can read my use case on the [dev branch](https://github.com/GwynHannay/google-photos-migrate/blob/dev/README.md) of my fork, though it's probably a bit out of date now as I'm still writing and running it.

I didn't want to add something to this repo that might be outside of what is intended here, though I also didn't want to have an instruction like "Go and clone this repo and run this script, then come and clone *this* repo and run *this* script", hence the fork. However, I would love to keep it all in the original place if you're open to it.

Uh, mine is also in Python but I can't easily rewrite it in Type Script because I've never used it before, haha.

**Comment by lukehmcc** [comment]
> Not to commandeer anyone else's post, but I do want to jump on the contribution bandwagon here. :-)
> 
> I found this repo really helpful for processing my mountain of Google Takeout photos and began utilising the additional script under `android-dups` but found my use case quite a bit more extensive. You can read my use case on the [dev branch](https://github.com/GwynHannay/google-photos-migrate/blob/dev/README.md) of my fork, though it's probably a bit out of date now as I'm still writing and running it.
> 
> I didn't want to add something to this repo that might be outside of what is intended here, though I also didn't want to have an instruction like "Go and clone this repo and run this script, then come and clone _this_ repo and run _this_ script", hence the fork. However, I would love to keep it all in the original place if you're open to it.
> 
> Uh, mine is also in Python but I can't easily rewrite it in Type Script because I've never used it before, haha.

This is quite cool, I haven't seen it before. Def a different beast you're tackling here though. Typescript isn't too hard if you wanna take a stab at it :p

**Comment by garzj** [comment]
> I'm currently maintaining [lukehmcc/exif-wrapper](https://github.com/lukehmcc/exif-wrapper) and think this automatic handling of takeout files would be very useful for this repo.
> 
> Would you be open to a PR to add a new flag like `--takeout` or something that would automatically decompress, organize, and fix the metadata on takeout files?
> 
> Currently this is done via a python script, but I could easily rewrite this in ts.

Sure, why not.

**Comment by garzj** [comment]
> Not to commandeer anyone else's post, but I do want to jump on the contribution bandwagon here. :-)
> 
> I found this repo really helpful for processing my mountain of Google Takeout photos and began utilising the additional script under `android-dups` but found my use case quite a bit more extensive. You can read my use case on the [dev branch](https://github.com/GwynHannay/google-photos-migrate/blob/dev/README.md) of my fork, though it's probably a bit out of date now as I'm still writing and running it.
> 
> I didn't want to add something to this repo that might be outside of what is intended here, though I also didn't want to have an instruction like "Go and clone this repo and run this script, then come and clone _this_ repo and run _this_ script", hence the fork. However, I would love to keep it all in the original place if you're open to it.
> 
> Uh, mine is also in Python but I can't easily rewrite it in Type Script because I've never used it before, haha.

As long as something helps others migrating from Google Photos, it's intended here I guess. So I wouldn't mind if you make a PR and link your work in the README :)

Merging the tools would only make sense if it's all Typescript IMO, then one could call them through separate subcommands.
